apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-html
  template:
    metadata:
      labels:
        app: nginx-html
    spec:
      containers:
      - name: nginx
        image: mohammedsafik/my-nginx-site:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-html-service
spec:
  type: NodePort
  selector:
    app: nginx-html
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
